<hr style = "border:2.5px solid #f78904ff"></hr>


# NUMPY BASICS
<hr style = "border:2.5px solid #f78904ff"></hr>

TANGENTE, KURT CLARENCE J.

In [67]:
import numpy as np
from scipy  import stats
from statistics import multimode

# 1D Array

In [68]:
my_array = ([1,2,3])
my_array

[1, 2, 3]

In [69]:
np.shape(my_array)

(3,)

# 2D Array

In [70]:
my_array = np.array([[1,2,3], 
                    [4,5,6]])
my_array

array([[1, 2, 3],
       [4, 5, 6]])

In [71]:
np.shape(my_array)

(2, 3)

In [72]:
t_array = my_array.T
t_array

array([[1, 4],
       [2, 5],
       [3, 6]])

In [73]:
np.shape(t_array)

(3, 2)

# Measures of Central tendency

In [74]:
# Jaguar vs Panther

resistance = np.array([
    [3,9.1,9.3,9.5,9.8,9.8,10.4,10.4,10.5,10.6,11],
    [9.1,9.1,9.1,9.2,9.2,9.9,10.1,10.8,11,20,np.nan]


])

In [75]:
np.shape(resistance)

(2, 11)

In [76]:
res_mean = np.nanmean(resistance,axis=1)



In [77]:
print("Jaguar mean:" + str((res_mean[0]).round(2))+ "ohms")
print ("Panther mean:" + str(res_mean[1]))


Jaguar mean:9.4ohms
Panther mean:10.75


In [91]:
print(f'Jaguar:{res_mean[0]:.2f} ohms')

Jaguar:9.40 ohms


In [79]:
res_median = np.nanmedian(resistance,axis=1)
res_median


array([9.8 , 9.55])

In [82]:
res_mode = stats.mode(resistance,axis=1)
res_mode


ModeResult(mode=array([9.8, 9.1]), count=array([2., 3.]))

In [92]:
jag_res = resistance[0]

print("Jaguar mode:")
for i in multimode(jag_res):
    print(f'{i}: ohms')


Jaguar mode:
9.8: ohms
10.4: ohms


In [97]:
pan_res = resistance[1]

print("Panther mode:")
for l in multimode(pan_res):
    print(f'{l}: ohms')


Panther mode:
9.1: ohms


# Measures of Central tendency

In [98]:
# Jaguar vs Panther

resistance = np.array([
    [3,9.1,9.3,9.5,9.8,9.8,10.4,10.4,10.5,10.6,11],
    [9.1,9.1,9.1,9.2,9.2,9.9,10.1,10.8,11,20,np.nan]


])

In [100]:
res_max = np.nanmax(resistance, axis=1)
res_min = np.nanmin(resistance, axis=1)

res_range = res_max - res_min
res_range

array([ 8. , 10.9])

In [109]:
print(f'Jaguar_range:{res_range[0]:.2f} ohms')
print(f'Panther_range:{res_range[1]:.2f} ohms')

Jaguar_range:8.00 ohms
Panther_range:10.90 ohms


In [108]:
res_Q1 = np.nanpercentile(resistance,25,axis=1)
res_Q1

array([9.4  , 9.125])

In [ ]:
print(f'Jaguar IQR: {res_Q1[0]:.2f} ohms')

Jaguuaq IQR: 9.40 ohms


In [114]:
res_var = np.nanvar(resistance,ddof=1,axis=1)

print(f'Jaguar Variance:{res_var[0]:.2f} ohms')

Jaguar Variance:4.86 ohms


In [116]:
res_std = np.nanstd(resistance,ddof=1,axis=1)

print(f'Jaguar Variance:{res_var[0]:.2f} ohms')
print(f' Variance:{res_var[1]:.2f} ohms')

Jaguar Variance:4.86 ohms
 Variance:11.08 ohms
